export type UiTone = "neutral" | "info" | "success" | "warning" | "danger";

const labels: Record<string, string> = {
  ADMIN: "Admin",
  GURU: "Guru",
  WALI: "Wali",
  SISWA: "Siswa",
  ACTIVE: "Aktif",
  INACTIVE: "Tidak aktif",
  GRADUATED: "Lulus",
  ARCHIVED: "Arsip",
  PENDING: "Menunggu",
  DRAFT: "Draf",
  SUBMITTED: "Dikirim",
  UNDER_REVIEW: "Sedang ditinjau",
  APPROVED: "Disetujui",
  REJECTED: "Ditolak",
  CANCELLED: "Dibatalkan",
  TRANSFERRED: "Dipindahkan",
  COMPLETED: "Selesai",
  FINAL: "Final",
  PRIVATE: "Pribadi",
  INTERNAL: "Internal",
  PENDAFTARAN: "Pendaftaran",
  MATERI: "Materi",
  USER: "Pengguna",
  RPP: "RPP",
  TEXT: "Teks",
  PDF: "PDF",
  IMAGE: "Gambar",
  VIDEO_LINK: "Tautan video",
  PUBLISHED: "Diterbitkan",
  FORM: "Isian langsung",
  FILE: "Berkas",
  SCHEDULED: "Terjadwal",
  CLASS_SESSION: "Sesi kelas",
  MODULE_RELEASE: "Rilis modul",
  ASSIGNMENT_DUE: "Tenggat tugas",
  QUIZ_DUE: "Tenggat kuis",
  EXAM: "Ujian",
  REMEDIAL_DUE: "Tenggat remedial",
  HOLIDAY: "Hari libur",
  ANNOUNCEMENT: "Pengumuman",
  ALL: "Semua",
  MATERIAL: "Materi",
  ASSIGNMENT: "Tugas",
  QUIZ: "Kuis",
  DISCUSSION: "Diskusi",
  VIEWED: "Sudah dilihat",
  GRADED: "Dinilai",
  PASSED: "Lulus",
  MANUAL: "Manual",
  NOT_STARTED: "Belum dimulai",
  IN_PROGRESS: "Sedang berjalan",
  ONLINE_TEXT: "Teks online",
  AUDIO: "Audio",
  VIDEO: "Video",
  EXTERNAL_LINK: "Tautan eksternal",
  OFFLINE_ACTIVITY: "Aktivitas luring",
  LATE: "Terlambat",
  NEEDS_REVISION: "Perlu revisi",
  COMPETENCY: "Kompetensi",
  ASSIGNED: "Ditugaskan",
  EXPIRED: "Kedaluwarsa",
  LATEST: "Nilai terbaru",
  HIGHEST: "Nilai tertinggi",
  AVERAGE: "Rata-rata",
  CAPPED: "Dengan batas nilai",
  OPEN: "Terbuka",
  INSTITUTION: "Lembaga",
  REVISED: "Direvisi",
  LOCKED: "Dikunci",
  ATTENDANCE: "Presensi",
  PROGRESS: "Progres",
  MISSING: "Belum ada nilai",
  EXEMPT: "Dikecualikan",
  REMEDIAL: "Remedial",
  CORRECTED: "Dikoreksi",
  INCOMPLETE: "Belum lengkap",
  COMPLETE: "Lengkap",
  HADIR: "Hadir",
  IZIN: "Izin",
  SAKIT: "Sakit",
  ALPA: "Alfa",
  TERLAMBAT: "Terlambat",
  PILIHAN_GANDA: "Pilihan ganda",
  MULTI_SELECT: "Pilihan lebih dari satu",
  BENAR_SALAH: "Benar atau salah",
  ISIAN_SINGKAT: "Isian singkat",
  MENJODOHKAN: "Menjodohkan",
  URUTAN: "Urutan",
  CLOZE: "Cloze",
  GAMBAR: "Gambar",
  LISTENING: "Menyimak",
  SPEAKING: "Berbicara",
  WRITING: "Menulis",
  READING: "Membaca",
  ROLEPLAY: "Bermain peran",
  ESAI: "Esai",
  NEEDS_REVIEW: "Perlu ditinjau",
  UNPAID: "Belum dibayar",
  PAID: "Lunas",
  OVERDUE: "Lewat jatuh tempo",
  REFUNDED: "Dikembalikan",
  FAILED: "Gagal",
  SENT: "Terkirim",
  RUNNING: "Berjalan",
  SUCCESS: "Berhasil",
  SKIPPED: "Dilewati",
  ENGLISH: "Bahasa Inggris",
  ARABIC: "Bahasa Arab",
  ARABIC_KIDS: "Arabic for Kids",
  NAHWU: "Nahwu",
  MATH_ACADEMIC_SUPPORT: "Math & Academic Support for Akhwat",
  LIMITED_SLOTS: "Slot terbatas",
  FULL: "Penuh / Waiting list",
  COMING_SOON: "Segera dibuka",
  TEACHER_ENTRY: "Input oleh guru",
  ONLINE_VIA_WALI: "Dikerjakan melalui akun Wali",
  EASY: "Mudah",
  MEDIUM: "Sedang",
  HARD: "Sulit",
  VOCABULARY: "Kosakata",
  GRAMMAR: "Tata bahasa",
  PRONUNCIATION: "Pelafalan",
  LITERACY: "Literasi",
  NUMERACY: "Numerasi",
  LOTS: "Berpikir dasar",
  MOTS: "Berpikir menengah",
  HOTS: "Berpikir tingkat lanjut",
  FORMATIVE: "Formatif",
  SUMMATIVE: "Sumatif",
  PLACEMENT: "Penempatan",
  DIAGNOSTIC: "Diagnostik",
};

const tones: Record<string, UiTone> = {
  ACTIVE: "success",
  APPROVED: "success",
  COMPLETED: "success",
  COMPLETE: "success",
  FINAL: "success",
  GRADED: "success",
  PAID: "success",
  PUBLISHED: "success",
  SENT: "success",
  SUCCESS: "success",
  DRAFT: "neutral",
  ARCHIVED: "neutral",
  CANCELLED: "neutral",
  REFUNDED: "neutral",
  INACTIVE: "neutral",
  LOCKED: "neutral",
  PENDING: "info",
  SUBMITTED: "info",
  UNDER_REVIEW: "info",
  IN_PROGRESS: "info",
  SCHEDULED: "info",
  OPEN: "info",
  NEEDS_REVIEW: "warning",
  NEEDS_REVISION: "warning",
  LATE: "warning",
  OVERDUE: "danger",
  FAILED: "danger",
  REJECTED: "danger",
  EXPIRED: "danger",
  MISSING: "danger",
};

const toneClasses: Record<UiTone, string> = {
  neutral: "bg-limo-neutral-100 text-limo-neutral-700",
  info: "bg-limo-blue-50 text-limo-blue-700",
  success: "bg-success-50 text-success-700",
  warning: "bg-warning-50 text-warning-800",
  danger: "bg-error-50 text-error-700",
};

export function formatUiLabel(value: string | null | undefined, fallback = "Tidak diketahui") {
  if (!value) return fallback;
  return labels[value] || fallback;
}

export function getUiTone(value: string | null | undefined): UiTone {
  return value ? tones[value] || "neutral" : "neutral";
}

export function getUiToneClass(value: string | null | undefined) {
  return toneClasses[getUiTone(value)];
}
