ALTER TABLE `BankSoal`
  ADD COLUMN `cognitiveLevel` VARCHAR(16) NOT NULL DEFAULT 'LOTS',
  ADD COLUMN `skill` VARCHAR(32) NOT NULL DEFAULT 'VOCABULARY',
  ADD COLUMN `difficulty` VARCHAR(16) NOT NULL DEFAULT 'EASY',
  ADD COLUMN `standard` VARCHAR(64) NULL,
  ADD COLUMN `assessmentType` VARCHAR(24) NOT NULL DEFAULT 'FORMATIVE';
