ALTER TABLE `BankSoal`
  MODIFY COLUMN `type` ENUM('PILIHAN_GANDA', 'MULTI_SELECT', 'BENAR_SALAH', 'ISIAN_SINGKAT', 'MENJODOHKAN', 'URUTAN', 'CLOZE', 'GAMBAR', 'LISTENING', 'SPEAKING', 'WRITING', 'READING', 'ROLEPLAY', 'ESAI') NOT NULL,
  ADD COLUMN `stimulusText` TEXT NULL,
  ADD COLUMN `mediaUrl` VARCHAR(500) NULL,
  ADD COLUMN `expectedAnswer` TEXT NULL,
  ADD COLUMN `structuredPayload` JSON NULL,
  ADD COLUMN `rubric` JSON NULL;

ALTER TABLE `JawabanUjian`
  ADD COLUMN `selectedOptions` JSON NULL,
  ADD COLUMN `shortAnswer` TEXT NULL,
  ADD COLUMN `structuredAnswer` JSON NULL;
