-- Tipe soal unggah file
ALTER TABLE `BankSoal`
  MODIFY `type` ENUM('PILIHAN_GANDA','MULTI_SELECT','BENAR_SALAH','ISIAN_SINGKAT','DROPDOWN','SKALA','RATING','TANGGAL','WAKTU','GRID','FILE_UPLOAD','MENJODOHKAN','URUTAN','CLOZE','GAMBAR','LISTENING','SPEAKING','WRITING','READING','ROLEPLAY','ESAI') NOT NULL;
