"use client";

type Item = { id: string; title: string; sourceType: string; sourceId: string | null; maxScore: number; normalizedScore: number | null; rawScore: number | null; status: string; isLate: boolean; feedbackSummary: string | null; isExtraCredit: boolean };
type Category = { id: string; name: string; weight: number; score: number | null; incomplete: boolean; items: Item[] };
type Row = { student: { id: string; name: string; nomorInduk: string }; categories: Category[]; calculatedScore: number | null; letterGrade: string | null; completionStatus: string; finalGrade: { publishedScore: unknown; status: string } | null };

export function GradebookViewer({ row, weightTotal, showSubmissionLinks = true }: { row: Row; weightTotal: number; showSubmissionLinks?: boolean }) {
  const finalScore = row.finalGrade?.publishedScore === null || row.finalGrade?.publishedScore === undefined ? null : Number(row.finalGrade.publishedScore);
  const incompleteItems = row.categories.flatMap((category) => category.items.filter((item) => ["MISSING", "SUBMITTED"].includes(item.status)).map((item) => `${category.name}: ${item.title}`));
  return <div className="space-y-5">
    <section className="tailadmin-card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-theme-xs font-semibold uppercase tracking-wide text-brand-500">Gradebook / {row.student.nomorInduk}</p><h2 className="mt-1 text-xl font-semibold text-gray-900">{row.student.name}</h2><p className="mt-1 text-theme-sm text-gray-500">Bobot kategori {weightTotal}% / status {row.completionStatus}</p></div><div className="rounded-2xl bg-success-50 px-5 py-3 text-center"><p className="text-3xl font-bold text-success-700">{finalScore ?? row.calculatedScore ?? "-"}</p><p className="text-theme-xs text-success-700">Nilai akhir {row.letterGrade ? `/ ${row.letterGrade}` : "belum publish"}</p></div></div></section>
    {incompleteItems.length > 0 ? <section className="rounded-2xl border border-warning-100 bg-warning-50 p-4"><p className="text-theme-sm font-semibold text-warning-800">Komponen belum selesai</p><ul className="mt-2 list-disc space-y-1 pl-5 text-theme-sm text-warning-800">{incompleteItems.slice(0, 8).map((item) => <li key={item}>{item}</li>)}</ul></section> : null}
    <section className="grid gap-4 md:grid-cols-2">{row.categories.map((category) => <article key={category.id} className="tailadmin-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-gray-900">{category.name}</h3><p className="text-theme-xs text-gray-500">Bobot {category.weight}%</p></div><span className="text-xl font-bold text-gray-900">{category.score ?? "-"}</span></div><div className="mt-4 space-y-2">{category.items.map((item) => <div key={item.id} className="rounded-xl bg-gray-50 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-theme-sm font-semibold text-gray-800" title={item.title}>{item.title}</p><p className="text-theme-xs text-gray-500">{item.sourceType}{item.isLate ? " / Terlambat" : ""} / {item.status}</p></div><p className="whitespace-nowrap text-theme-sm font-semibold text-gray-700">{item.normalizedScore ?? "-"}</p></div>{item.feedbackSummary ? <p className="mt-2 whitespace-pre-line text-theme-xs leading-5 text-gray-600">{item.feedbackSummary}</p> : null}{showSubmissionLinks && item.sourceType === "ASSIGNMENT" && item.sourceId ? <a href={`/siswa/tugas/${item.sourceId}`} className="mt-2 inline-block text-theme-xs font-semibold text-brand-600">Buka submission</a> : null}</div>)}</div></article>)}</section>
  </div>;
}
